<a href="https://colab.research.google.com/github/quamrl-hoda/pwAssignment_/blob/main/numpyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1 Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [4]:
import numpy as np

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int64


### 2 Given a NumPy array 'arr', check if its data type is float64.


In [10]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)


float64


###  3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


In [14]:
arr = np.array([1+2j, 3+2j, 5+6j]
)
print(arr.dtype)

complex128


###  4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [15]:
arr = np.array([1, 2, 3, 4, 5])

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3. 4. 5.]
float32


###  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [102]:
arr = np.array([1.123456789, 2.987654321, 3.543210987], dtype=np.float64)

arr_float32 = arr.astype(np.float32)

print(arr_float32)
print(arr_float32.dtype)


[1.1234568 2.9876542 3.543211 ]
float32


###  6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data


In [18]:
import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

arr = np.array([1, 2, 3, 4, 5])
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)


Shape: (5,)
Size: 5
Data Type: int64


### 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [19]:
import numpy as np

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)

print("Dimensionality:", dimension)


Dimensionality: 2


###  8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [20]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)
item_size, total_size = item_size_info(arr)

print("Item Size:", item_size, "bytes")
print("Total Size:", total_size, "bytes")


Item Size: 4 bytes
Total Size: 20 bytes


###  9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


In [21]:
import numpy as np

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides:", strides)


Strides: (24, 8)


###  10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [22]:
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


###  11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [23]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)

print("Zeros Array:", zeros_array)


Zeros Array: [0. 0. 0. 0. 0.]


###  12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [103]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("Ones Matrix:")
print(ones_matrix)


Ones Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [25]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Generated Range Array:", range_array)


Generated Range Array: [1 3 5 7 9]


###  14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [26]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 1.0
stop = 5.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Generated Linear Space Array:", linear_space_array)


Generated Linear Space Array: [1. 2. 3. 4. 5.]


###  15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [27]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)

print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###  16. Write a function that takes a Python list and converts it into a NumPy array.


In [28]:
import numpy as np

def list_to_array(py_list):
    return np.array(py_list)

py_list = [1, 2, 3, 4, 5]
np_array = list_to_array(py_list)

print("Converted NumPy Array:", np_array)


Converted NumPy Array: [1 2 3 4 5]


###  17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr_view = arr.view()

arr[0] = 10

print("Original Array:", arr)
print("Array View:", arr_view)


Original Array: [10  2  3  4  5]
Array View: [10  2  3  4  5]


### 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


In [30]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)  # Concatenate along the specified axis

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenated_array_axis0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated Array along axis 0:")
print(concatenated_array_axis0)

concatenated_array_axis1 = concatenate_arrays(arr1, arr2, axis=1)
print("\nConcatenated Array along axis 1:")
print(concatenated_array_axis1)


Concatenated Array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated Array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


###  19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [31]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Concatenated Array:")
print(concatenated_array)


Concatenated Array:
[[1 2 5]
 [3 4 6]]


###  20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [32]:
import numpy as np

def vertical_stack_arrays(arrays_list):
    return np.vstack(arrays_list)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

arrays = [arr1, arr2, arr3]

stacked_array = vertical_stack_arrays(arrays)

print("Vertically Stacked Array:")
print(stacked_array)


Vertically Stacked Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [33]:
import numpy as np

def create_array_in_range(start, stop, step):
    return np.arange(start, stop + 1, step)

start = 1
stop = 10
step = 2

array_in_range = create_array_in_range(start, stop, step)

print("Array within the specified range:", array_in_range)


Array within the specified range: [1 3 5 7 9]


###  22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [34]:
import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

equally_spaced_values = generate_equally_spaced_values()

print("Equally Spaced Values:", equally_spaced_values)


Equally Spaced Values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


###  23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [35]:
import numpy as np

def generate_logarithmic_values():
    return np.logspace(0, 3, 5)

logarithmic_values = generate_logarithmic_values()

print("Logarithmically Spaced Values:", logarithmic_values)


Logarithmically Spaced Values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


###  24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [36]:
import numpy as np
import pandas as pd

random_array = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       58       61       15
1       20       67       81
2       93       15        5
3       49       62       87
4       47       11       66


###  25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [37]:
import pandas as pd
import numpy as np

def replace_negative_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])  # Replace negative values with zeros
    return df

data = {'Column1': [10, -5, 20, -3, 15],
        'Column2': [8, 2, -10, 3, -1]}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negative_with_zero(df, 'Column1')

print("\nModified DataFrame (Negative values in 'Column1' replaced with 0):")
print(df)


Original DataFrame:
   Column1  Column2
0       10        8
1       -5        2
2       20      -10
3       -3        3
4       15       -1

Modified DataFrame (Negative values in 'Column1' replaced with 0):
   Column1  Column2
0       10        8
1        0        2
2       20      -10
3        0        3
4       15       -1


###  26. Access the 3rd element from the given NumPy array.


In [38]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("3rd element:", third_element)


3rd element: 30


###  27. Retrieve the element at index (1, 2) from the 2D NumPy array.


In [39]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]

print("Element at index (1, 2):", element)


Element at index (1, 2): 6


###  28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [40]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

greater_than_five = arr[arr > 5]

print("Elements greater than 5:", greater_than_five)


Elements greater than 5: [ 8 10  7]


###  29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]

print("Sliced Array:", sliced_arr)


Sliced Array: [3 4 5 6]


###  30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [42]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[1:3, 0:2]
f
print("Sub-array:")
print(sub_array)


Sub-array:
[[4 5]
 [7 8]]


### 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [43]:
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    return arr_2d[indices[:, 0], indices[:, 1]]

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = np.array([[0, 1],
                    [2, 0],
                    [1, 2]])

extracted_elements = extract_elements_by_indices(arr_2d, indices)

print("Extracted Elements:", extracted_elements)


Extracted Elements: [20 70 60]


###  32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [44]:
import numpy as np

def filter_elements_by_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 5, 8, 12, 3, 7, 10])
threshold = 6

filtered_elements = filter_elements_by_threshold(arr, threshold)

print("Filtered Elements:", filtered_elements)


Filtered Elements: [ 8 12  7 10]


###  33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [45]:
import numpy as np

def extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices):
    return arr_3d[row_indices, col_indices, depth_indices]

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])
depth_indices = np.array([2, 1, 0])

extracted_elements = extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices)

print("Extracted Elements:", extracted_elements)


Extracted Elements: [ 6 11 25]


###  34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [46]:
import numpy as np

def filter_elements_with_conditions(arr, condition1, condition2):
    return arr[condition1 & condition2]

arr = np.array([1, 5, 8, 12, 3, 7, 10])

condition1 = arr > 5
condition2 = arr % 2 == 0

filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)

print("Filtered Elements:", filtered_elements)


Filtered Elements: [ 8 12 10]


###  35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [47]:
import numpy as np

def extract_elements_by_indices(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

extracted_elements = extract_elements_by_indices(arr_2d, row_indices, col_indices)

print("Extracted Elements:", extracted_elements)


Extracted Elements: [20 60 70]


###  36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [48]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print("Resulting Array:")
print(result)


Resulting Array:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


###  37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [104]:
import numpy as np

# Create arrays arr1 and arr2
arr1 = np.array([[2, 4, 6]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Reshape arr1 for broadcasting compatibility
# The new shape will be (3, 1), allowing it to be broadcast across columns of arr2
arr1_reshaped = arr1.reshape(3,1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1_reshaped

print("Resulting Array:")
print(result)

Resulting Array:
[[ 2  4  6  8]
 [20 24 28 32]
 [54 60 66 72]]


###  38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [51]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

arr1_reshaped = arr1.T

result = arr2 + arr1_reshaped

print("Resulting Array:")
print(result)


Resulting Array:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


###  39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [52]:
import numpy as np

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print("Resulting Array:")
print(result)


Resulting Array:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


###  40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [53]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8],
                 [9, 10]])

arr2_reshaped = arr2[:, :, np.newaxis]

result = arr1 * arr2_reshaped

print("Resulting Array:")
print(result)


Resulting Array:
[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


###  41. Calculate column-wise mean for the given array:


In [54]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_mean)


Column-wise mean: [2.5 3.5 4.5]


###  42. Find maximum value in each row of the given array:


In [55]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max = np.max(arr, axis=1)

print("Maximum value in each row:", row_max)


Maximum value in each row: [3 6]


###  43. For the given array, find indices of maximum value in each column.


In [56]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

column_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:", column_max_indices)


Indices of maximum value in each column: [1 1 1]


### 44. For the given array, apply custom function to calculate moving sum along rows.


In [57]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

def moving_sum(arr, window_size=2):
    return np.apply_along_axis(lambda x: np.convolve(x, np.ones(window_size), mode='valid'), axis=1, arr=arr)

moving_sum_result = moving_sum(arr)

print("Moving sum along rows:", moving_sum_result)


Moving sum along rows: [[ 3.  5.]
 [ 9. 11.]]


###  45. In the given array, check if all elements in each column are even.


In [58]:
import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

all_even = np.all(arr % 2 == 0, axis=0)

print("All elements in each column are even:", all_even)


All elements in each column are even: [False False False]


### 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.


In [59]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2, 3
reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:")
print(reshaped_matrix)


Reshaped matrix:
[[1 2 3]
 [4 5 6]]


###  47. Create a function that takes a matrix as input and returns the flattened array.


In [60]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("Flattened array:", flattened_array)


Flattened array: [1 2 3 4 5 6]


### 48. Write a function that concatenates two given arrays along a specified axis.


In [61]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Concatenated along axis 0:")
print(concatenated_array_axis0)

print("Concatenated along axis 1:")
print(concatenated_array_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


### 49. Create a function that splits an array into multiple sub-arrays along a specified axis.


In [62]:
import numpy as np

def split_array(array, num_splits, axis=0):
    return np.split(array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

split_arrays_axis0 = split_array(original_array, 3, axis=0)

split_arrays_axis1 = split_array(original_array, 3, axis=1)

print("Split along axis 0:")
for sub_array in split_arrays_axis0:
    print(sub_array)

print("\nSplit along axis 1:")
for sub_array in split_arrays_axis1:
    print(sub_array)


Split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


###  50. Write a function that inserts and then deletes elements from a given array at specified indices.


In [63]:
import numpy as np

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    array_after_insert = np.insert(original_array, indices_to_insert, values_to_insert)

    array_after_delete = np.delete(array_after_insert, indices_to_delete)

    return array_after_insert, array_after_delete

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]
values_to_insert = [10, 11]

indices_to_delete = [1, 3]

array_after_insert, array_after_delete = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Array after insertion:")
print(array_after_insert)

print("\nArray after deletion:")
print(array_after_delete)


Array after insertion:
[ 1  2 10  3  4 11  5]

Array after deletion:
[ 1 10  4 11  5]


###  51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [64]:
import numpy as np

arr1 = np.random.randint(0, 10, size=5)

arr2 = np.arange(1, 6)

result = arr1 + arr2

print("Array 1 (random integers):", arr1)
print("Array 2 (integers from 1 to 5):", arr2)
print("Element-wise addition result:", result)


Array 1 (random integers): [8 3 1 8 6]
Array 2 (integers from 1 to 5): [1 2 3 4 5]
Element-wise addition result: [ 9  5  4 12 11]


### 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [65]:
import numpy as np

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr1 - arr2

print("Array 1 (sequential integers from 10 to 1):", arr1)
print("Array 2 (integers from 1 to 10):", arr2)
print("Element-wise subtraction result:", result)


Array 1 (sequential integers from 10 to 1): [10  9  8  7  6  5  4  3  2  1]
Array 2 (integers from 1 to 10): [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


###  53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [67]:
import numpy as np

arr1 = np.random.randint(0, 10, size=5)

arr2 = np.arange(1, 6)

result = arr1 * arr2

print("Array 1 (random integers):", arr1)
print("Array 2 (integers from 1 to 5):", arr2)
print("Element-wise multiplication result:", result)


Array 1 (random integers): [2 6 2 8 7]
Array 2 (integers from 1 to 5): [1 2 3 4 5]
Element-wise multiplication result: [ 2 12  6 32 35]


###  54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [68]:
import numpy as np

arr1 = np.arange(2, 11, 2)

arr2 = np.arange(1, 6)

result = arr1 / arr2

print("Array 1 (even integers from 2 to 10):", arr1)
print("Array 2 (integers from 1 to 5):", arr2)
print("Element-wise division result:", result)


Array 1 (even integers from 2 to 10): [ 2  4  6  8 10]
Array 2 (integers from 1 to 5): [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


### 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [69]:
import numpy as np

arr1 = np.arange(1, 6)

arr2 = np.flip(arr1)

result = arr1 ** arr2

print("Array 1 (integers from 1 to 5):", arr1)
print("Array 2 (reversed integers from 1 to 5):", arr2)
print("Element-wise exponentiation result:", result)


Array 1 (integers from 1 to 5): [1 2 3 4 5]
Array 2 (reversed integers from 1 to 5): [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


###  56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.


In [70]:
import numpy as np

def count_substring_occurrences(arr, substring):
    count_array = np.char.count(arr, substring)

    return np.sum(count_array)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

result = count_substring_occurrences(arr, substring)
print(f"Occurrences of '{substring}':", result)


Occurrences of 'hello': 3


###  57. Write a function that extracts uppercase characters from a NumPy array of strings.


In [ ]:
import numpy as np

def extract_uppercase(arr):
    uppercase_chars = []

    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_chars.append(char)

    return uppercase_chars

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

result = extract_uppercase(arr)
print("Uppercase characters:", result)


### 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.


In [73]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    updated_arr = np.char.replace(arr, old_substring, new_substring)

    return updated_arr

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'

result = replace_substring(arr, old_substring, new_substring)
print("Updated array:", result)


Updated array: ['orange' 'banana' 'grape' 'pineorange']


###  59. Write a function that concatenates strings in a NumPy array element-wise.


In [74]:
import numpy as np

def concatenate_strings(arr1, arr2):
    concatenated_array = np.char.add(arr1, arr2)

    return concatenated_array

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print("Concatenated array:", result)


Concatenated array: ['HelloOpen' 'WorldAI']


###  60. Write a function that finds the length of the longest string in a NumPy array.


In [75]:
import numpy as np

def longest_string_length(arr):
    string_lengths = np.vectorize(len)(arr)
    return np.max(string_lengths)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string_length(arr)
print("Length of the longest string:", result)


Length of the longest string: 9


###  61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [76]:
import numpy as np

data = np.random.randint(1, 1001, size=100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Dataset:", data)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Dataset: [518 561 222 149 119 932 752 312 515 525 727 989 646 510 675 897 524 338
 635 250 847 721  98 450 425 685 594 313 739 657  43 492 993 525 434 138
 313 717 805 151 482 711 492 344 962 696 125 707 759 469 736 543 524 709
 343 565 319 403  90 840 165 402 879 532  84 549 223  11 902 927 782 574
 331 439 333 802 176 431   8 629 831 501 744 787 592 618 121 352  68 575
  43   8 788 589 997 502 168 839 980 216]
Mean: 512.53
Median: 524.5
Variance: 73041.66910000001
Standard Deviation: 270.26222285032736


###  62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [77]:
import numpy as np

random_numbers = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print("Random Numbers:", random_numbers)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Random Numbers: [82 22 54 53 22 37 85  1 57  2 21 66 88 15 22 65 56 20 34 19 47 56 24 69
 37 25 86 94 77 35  2 93 81 94 27 36 74 42 83 43 19 49 52 25 83 58  7 23
  7 74]
25th Percentile: 22.25
75th Percentile: 72.75


###  63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [78]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

correlation_matrix = np.corrcoef(array1, array2)

print("Correlation Coefficient Matrix:")
print(correlation_matrix)


Correlation Coefficient Matrix:
[[ 1. -1.]
 [-1.  1.]]


###  64. Create two matrices and perform matrix multiplication using NumPy's dot function.



In [79]:
import numpy as np

matrix_a = np.array([[1, 2, 3],
                      [4, 5, 6]])

matrix_b = np.array([[7, 8],
                      [9, 10],
                      [11, 12]])

result_matrix = np.dot(matrix_a, matrix_b)

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResult of Matrix Multiplication (A dot B):")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication (A dot B):
[[ 58  64]
 [139 154]]


###  65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [80]:
import numpy as np

random_numbers = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(random_numbers, 10)
percentile_50 = np.percentile(random_numbers, 50)
percentile_90 = np.percentile(random_numbers, 90)
quartile_1 = np.percentile(random_numbers, 25)
quartile_3 = np.percentile(random_numbers, 75)

print("Random Numbers:", random_numbers)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", quartile_1)
print("Third Quartile (Q3):", quartile_3)


Random Numbers: [ 310  161  999   52  779  806  442  691  646  316 1000  415  375  395
  709  197  135  969   69  749  507  370  769  273  793  817   60  507
  808  853  280  219   62  116  677  520  288  387   72   59  792  945
  414  685  857  122  285  160  518  749]
10th Percentile: 71.7
50th Percentile (Median): 428.5
90th Percentile: 853.4
First Quartile (Q1): 232.5
Third Quartile (Q3): 764.0


###  66. Create a NumPy array of integers and find the index of a specific element.


In [81]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

element_to_find = 50

index_of_element = np.where(array == element_to_find)

print("Array:", array)
print("Index of element", element_to_find, ":", index_of_element[0])


Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50 : [4]


###  67. Generate a random NumPy array and sort it in ascending order.


In [82]:
import numpy as np

random_array = np.random.randint(10, 1001, size=50)

sorted_array = np.sort(random_array)

print("Random Array:", random_array)
print("Sorted Array:", sorted_array)


Random Array: [378 953 791 432 741 473 158 789 622  92 570 104 343 976 409 687  32 861
 617 955 631 697 169 977 513 949  20 936 187 127 474 172 888 642  48 306
 996 527 562 200 244 333 362 695 132 304 333 315 917  45]
Sorted Array: [ 20  32  45  48  92 104 127 132 158 169 172 187 200 244 304 306 315 333
 333 343 362 378 409 432 473 474 513 527 562 570 617 622 631 642 687 695
 697 741 789 791 861 888 917 936 949 953 955 976 977 996]


###  68. Filter elements >20  in the given NumPy array.


In [83]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_elements = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Elements (> 20):", filtered_elements)


Original Array: [12 25  6 42  8 30]
Filtered Elements (> 20): [25 42 30]


###  69. Filter elements which are divisible by 3 from a given NumPy array.


In [84]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

filtered_elements = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Elements (Divisible by 3):", filtered_elements)


Original Array: [ 1  5  8 12 15]
Filtered Elements (Divisible by 3): [12 15]


###  70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.


In [85]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered_elements = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:", arr)
print("Filtered Elements (≥ 20 and ≤ 40):", filtered_elements)


Original Array: [10 20 30 40 50]
Filtered Elements (≥ 20 and ≤ 40): [20 30 40]


###  71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.


In [86]:
import numpy as np

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Array:", arr)
print("Byte Order:", byte_order)


Array: [1 2 3]
Byte Order: =


### 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.


In [87]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(inplace=True)

print("Byteswapped Array:", arr)


Byteswapped Array: [16777216 33554432 50331648]


### 73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.


In [88]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_array = arr.newbyteorder()

print("Original Array:", arr)
print("Swapped Byte Order Array:", swapped_array)


Original Array: [1 2 3]
Swapped Byte Order Array: [16777216 33554432 50331648]


### 74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.


In [89]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

native_order = '=' if sys.byteorder == 'little' else '>'

if arr.dtype.byteorder != native_order:
    swapped_array = arr.newbyteorder()
else:
    swapped_array = arr

print("Original Array:", arr)
print("Swapped Byte Order Array:", swapped_array)


Original Array: [1 2 3]
Swapped Byte Order Array: [1 2 3]


### 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.


In [91]:
import numpy as np
import sys

arr = np.array([1, 2, 3], dtype=np.int32)

array_byte_order = arr.dtype.byteorder

system_byte_order = '=' if sys.byteorder == 'little' else '>'

print("Array Byte Order:", array_byte_order)
print("System Native Byte Order:", system_byte_order)

if array_byte_order != system_byte_order and array_byte_order != '|':
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Array Byte Order: =
System Native Byte Order: =
Byte swapping is not necessary.


### 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [92]:
import numpy as np

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 99

print("Original Array (arr1):", arr1)
print("Copied Array (copy_arr):", copy_arr)


Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied Array (copy_arr): [99  2  3  4  5  6  7  8  9 10]


###  77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [93]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

view_slice = matrix[1:, 1:]

view_slice[0, 0] = 99

print("Original Matrix:")
print(matrix)
print("\nView Slice:")
print(view_slice)


Original Matrix:
[[ 2  3  7]
 [ 6 99  4]
 [ 8  2  3]]

View Slice:
[[99  4]
 [ 2  3]]


###  78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [94]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:, 1:]

view_b += 5

print("Original Array (array_a):")
print(array_a)
print("\nModified Slice (view_b):")
print(view_b)


Original Array (array_a):
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]

Modified Slice (view_b):
[[10 11]
 [13 14]
 [16 17]]


###  79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [95]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99

print("Original Array (orig_array):")
print(orig_array)
print("\nReshaped View (reshaped_view):")
print(reshaped_view)


Original Array (orig_array):
[[99  2  3  4]
 [ 5  6  7  8]]

Reshaped View (reshaped_view):
[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


###  80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [96]:
import numpy as np

data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5].copy()

if data_copy.size > 0:
    data_copy[0] = 99

print("Original Array (data):")
print(data)
print("\nCopy of Elements Greater Than 5 (data_copy):")
print(data_copy)


Original Array (data):
[[10  9  8  4]
 [ 1  7  6  6]
 [ 5  5  2  7]]

Copy of Elements Greater Than 5 (data_copy):
[99  9  8  7  6  6  7]


###  81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [97]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

C_add = A + B

C_sub = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition of A and B (C_add):")
print(C_add)
print("\nSubtraction of A and B (C_sub):")
print(C_sub)


Matrix A:
[[ 9  1  7]
 [ 9  3  5]
 [ 8 10  8]]

Matrix B:
[[3 3 6]
 [6 9 7]
 [6 5 5]]

Addition of A and B (C_add):
[[12  4 13]
 [15 12 12]
 [14 15 13]]

Subtraction of A and B (C_sub):
[[ 6 -2  1]
 [ 3 -6 -2]
 [ 2  5  3]]


###  82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


In [98]:
import numpy as np

C = np.random.randint(1, 11, size=(3, 2))

D = np.random.randint(1, 11, size=(2, 4))

result = np.dot(C, D)

print("Matrix C (3x2):")
print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of Matrix Multiplication (C dot D):")
print(result)


Matrix C (3x2):
[[5 6]
 [2 2]
 [2 6]]

Matrix D (2x4):
[[ 3  3 10  1]
 [ 8  4  8  4]]

Result of Matrix Multiplication (C dot D):
[[63 39 98 29]
 [22 14 36 10]
 [54 30 68 26]]


###  83. Create a matrix `E` and find its transpose.


In [99]:
import numpy as np

E = np.random.randint(1, 11, size=(3, 4))

E_transpose = E.T

print("Original Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)


Original Matrix E:
[[ 3  8 10  5]
 [ 5  7 10  7]
 [ 4  2  2  5]]

Transpose of Matrix E:
[[ 3  5  4]
 [ 8  7  2]
 [10 10  2]
 [ 5  7  5]]


###  84. Generate a square matrix `F` and compute its determinant.


In [100]:
import numpy as np

F = np.random.randint(1, 11, size=(3, 3))

determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("\nDeterminant of Matrix F:")
print(determinant_F)


Matrix F:
[[ 9  5  6]
 [10  6  8]
 [ 7  5  2]]

Determinant of Matrix F:
-24.000000000000014


###  85. Create a square matrix `G` and find its inverse.

In [101]:
import numpy as np

G = np.random.randint(1, 11, size=(3, 3))

determinant_G = np.linalg.det(G)

if determinant_G != 0:
    G_inverse = np.linalg.inv(G)

    print("Matrix G:")
    print(G)
    print("\nDeterminant of Matrix G:")
    print(determinant_G)
    print("\nInverse of Matrix G:")
    print(G_inverse)
else:
    print("Matrix G is singular and cannot be inverted.")


Matrix G:
[[ 9  1 10]
 [ 3  4  9]
 [ 6  9 10]]

Determinant of Matrix G:
-315.0

Inverse of Matrix G:
[[ 0.13015873 -0.25396825  0.0984127 ]
 [-0.07619048 -0.0952381   0.16190476]
 [-0.00952381  0.23809524 -0.1047619 ]]
